== RRT: Registrar Remark Token

This is a Rust implementation of my RRT token. Same than what I did in Typescript beside the bugs I found in the initial Typescript implementation while writting the Rust version !

WARNING: Currently the wording is not ideal as I use `token` to refer to both an **RRT Token** but also the **token** inside of it. The inner token is also referred as **secret token**. This should be rework.

=== Versions

The first two digits are the registrar index. The 2 next are for a version number.
That allows evolving how the token is encoded/decoded.

The versions are encoded as HEX fro 00 to FF. So we have 255 options.

In my first version, I encoded the checksum on a single digit but I never used that version. I will allocated 2 bytes for the checksum to allow more complex and robust (against position swapping for instance) checksums.

The initial version also did not inlucde the networkId, I will add it as it may help when people run simultaneous verifications and paste the wrong token on the wrong chain.

Here is the history / description of the versions:

==== V00: 20 chars

This is the first version. The checksum is a rather naive (=simple) custom implementation. This checksum implementation is NOT robust against position swapping. So ABCDEF and BACDEF will have the same checksum :(

The data field can only contain the secret token (8 chars).

The checksum is a single u8

WANRNING: This version should not be used in production but can be useful for testing.

==== V01: 21 chars

This version uses a Fletcher 16 checksum so the checksum is coded as `[u8; 2]`.

In this version, the `Data` field is a variant that supports a few other options such as `Ready`, used by the user to signal events onchain for which there is no other extrinsic/event.

==== V02

This is a planned test using a Blake hash on 2 bytes.
